### ISSUE TITLE
Comparison - shove vs gorush

### ISSUE THREAD

**Issue by rrjanbiah** [pennersr/shove#3]
Are there any marketing pitch by comparing with gorush? (apart from the items mentioned in https://github.com/appleboy/gorush/issues/386#issuecomment-479191179 ?)

TIA

**Comment by pennersr** [comment]
I see that they now closed that issue over there. I only glanced at the solution, but it seems that they solved it by having the push server emit a callback request, which would mean that you need to have both sides (push server and your own service) up and running in order to not miss any messages. In contrast, Shove has this on its features list:

> Less moving parts: when using Redis, you can push directly to the queue, bypassing the need for the Shove server to be up and running.

So, you can take both sides independently offline and no data will be lost.

FWIW, Shove also has Telegram support. 

Anyway, no time was spent on marketing or putting up a fancy website -- it was build to solve a need, and it has been happily pushing out millions of notifications so far, and still is.

**Comment by rrjanbiah** [comment]
@pennersr I appreciate the comments and spirit. But, if the library is too good, at least a small comparison table in the README will help in some marketing.
